<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-22 05:08

from django.db import migrations, models
=======
# Generated by Django 4.2.2 on 2023-06-22 06:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
>>>>>>> 470b6791fc676730c20018a85efb7b342bacce40


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=255, verbose_name='名前')),
                ('text', models.TextField(verbose_name='コメント内容')),
=======
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='カテゴリ名')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='chat.category', verbose_name='カテゴリ')),
                ('tags', models.ManyToManyField(blank=True, null=True, to='chat.tag', verbose_name='タグ')),
>>>>>>> 470b6791fc676730c20018a85efb7b342bacce40
            ],
        ),
    ]
