# Generated by Django 4.2.2 on 2023-06-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='upname',
            field=models.CharField(default='名無し', max_length=255, verbose_name='名前'),
        ),
    ]
