# Generated by Django 4.2.2 on 2023-06-23 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Kiji',
        ),
    ]
