# Generated by Django 4.2.2 on 2023-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_article_kiji'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_no', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
