# Generated by Django 4.2.2 on 2023-06-30 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='名無し', max_length=100, verbose_name='名前\u3000\u3000\u3000\u3000'),
        ),
        migrations.AlterField(
            model_name='kiji',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日\u3000'),
        ),
        migrations.AlterField(
            model_name='kiji',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.tag', verbose_name='タグ\u3000\u3000'),
        ),
        migrations.AlterField(
            model_name='kiji',
            name='text',
            field=models.TextField(verbose_name='本文\u3000\u3000'),
        ),
    ]
