# Generated by Django 4.2.2 on 2023-06-26 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('title', models.CharField(max_length=255, verbose_name='教科')),
                ('text', models.TextField(verbose_name='内容')),
            ],
        ),
    ]
