# Generated by Django 4.2.2 on 2023-06-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/', verbose_name='宿題'),
        ),
    ]
