# Generated by Django 4.2.2 on 2023-06-28 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='homework',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='なまえ'),
        ),
    ]
