# Generated by Django 4.2.2 on 2023-06-30 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='homework.category', verbose_name='きょうか'),
        ),
    ]
