# Generated by Django 4.2.2 on 2023-06-22 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='教科名')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付')),
                ('text', models.TextField(verbose_name='必要な物')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='timetable.subject', verbose_name='教科')),
            ],
        ),
    ]
