# Generated by Django 4.2.2 on 2023-06-22 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
