# Generated by Django 4.2.2 on 2023-06-27 01:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datetime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='日付')),
            ],
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('day',)},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject',
        ),
        migrations.AddField(
            model_name='timetable',
            name='FifthPeriod',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='FifthPeriod', to='timetable.subject', verbose_name='5限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='FirstPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FirstPeriod', to='timetable.subject', verbose_name='1限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='FourthPeriod',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='FourthPeriod', to='timetable.subject', verbose_name='4限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='SecondPeriod',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='SecondPeriod', to='timetable.subject', verbose_name='2限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='SixthPeriod',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='SixthPeriod', to='timetable.subject', verbose_name='6限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='ThirdPeriod',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ThirdPeriod', to='timetable.subject', verbose_name='3限'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='text',
            field=models.TextField(verbose_name='必要な物リスト'),
        ),
        migrations.CreateModel(
            name='Lunchmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='献立画像')),
                ('menu', models.TextField(default='1', verbose_name='献立')),
                ('explain', models.TextField(default='1', verbose_name='説明')),
                ('day', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='timetable.datetime', verbose_name='給食日付')),
            ],
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='timetable.datetime', verbose_name='時間割日付'),
        ),
    ]
