# Generated by Django 4.2.2 on 2023-06-27 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_datetime_alter_timetable_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.PROTECT, to='timetable.datetime', verbose_name='日付'),
        ),
    ]
