# Generated by Django 4.2.2 on 2023-06-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_alter_timetable_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='subject',
            new_name='subject_1',
        ),
    ]
