# Generated by Django 4.2.2 on 2023-06-27 02:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_alter_timetable_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunchmenu',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timetable.timetable', verbose_name='紐づく時間割'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
        migrations.DeleteModel(
            name='Datetime',
        ),
    ]
