# Generated by Django 4.2.2 on 2023-06-26 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_rename_subject_timetable_subject_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_1',
        ),
        migrations.AddField(
            model_name='timetable',
            name='FifthPeriod',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='FifthPeriod', to='timetable.subject', verbose_name='5限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='FirstPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FirstPeriod', to='timetable.subject', verbose_name='1限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='FourthPeriod',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='FourthPeriod', to='timetable.subject', verbose_name='4限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='SecondPeriod',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='SecondPeriod', to='timetable.subject', verbose_name='2限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='SixthPeriod',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='SixthPeriod', to='timetable.subject', verbose_name='6限'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='ThirdPeriod',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ThirdPeriod', to='timetable.subject', verbose_name='3限'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='text',
            field=models.TextField(verbose_name='必要な物リスト'),
        ),
    ]
