# Generated by Django 4.2.2 on 2023-06-26 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_remove_timetable_subject_1_timetable_fifthperiod_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ('day',)},
        ),
    ]
