# Generated by Django 4.2.2 on 2023-06-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_alter_lunchmenu_day_alter_timetable_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='explain',
            field=models.TextField(default='1', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='献立画像'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='menu',
            field=models.TextField(default='1', verbose_name='献立'),
        ),
        migrations.DeleteModel(
            name='Lunchmenu',
        ),
    ]
