# Generated by Django 4.2.2 on 2023-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_alter_timetable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunchmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='商品画像')),
            ],
        ),
    ]
