# Generated by Django 4.2.2 on 2023-06-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_timetable_explain_timetable_image_timetable_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='explain',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lunchmenu_images/', verbose_name='献立画像'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='menu',
            field=models.TextField(verbose_name='献立'),
        ),
    ]
