# Generated by Django 4.2.2 on 2023-06-29 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_timetable_explain_alter_timetable_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='fifthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容5'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='firsttext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容1'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='fourthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容4'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='secondtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容2'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='sixthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容6'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='thirdtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容3'),
        ),
    ]
