# Generated by Django 4.2.2 on 2023-06-30 00:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_timetable_fifthtext_timetable_firsttext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='FifthPeriod',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='FifthPeriod', to='timetable.subject', verbose_name='５時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='FirstPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FirstPeriod', to='timetable.subject', verbose_name='１時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='FourthPeriod',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='FourthPeriod', to='timetable.subject', verbose_name='４時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='SecondPeriod',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='SecondPeriod', to='timetable.subject', verbose_name='２時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='SixthPeriod',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='SixthPeriod', to='timetable.subject', verbose_name='６時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='ThirdPeriod',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='ThirdPeriod', to='timetable.subject', verbose_name='３時間目'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='日付\u3000\u3000'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='explain',
            field=models.TextField(verbose_name='説明\u3000\u3000'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fifthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='firsttext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='fourthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='menu',
            field=models.TextField(verbose_name='献立\u3000\u3000'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='secondtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='sixthtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='text',
            field=models.TextField(verbose_name='必要な物'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='thirdtext',
            field=models.CharField(default='', max_length=30, verbose_name='授業内容'),
        ),
    ]
