# Generated by Django 4.2.2 on 2023-06-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_delete_lunchmenu_timetable_explain_timetable_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunchmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goods_images/', verbose_name='献立画像')),
                ('menu', models.TextField(default='1', verbose_name='献立')),
                ('explain', models.TextField(default='1', verbose_name='説明')),
            ],
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='explain',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='image',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='menu',
        ),
    ]
