# Generated by Django 4.2.2 on 2023-06-23 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_alter_timetable_subject_1_alter_timetable_subject_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='subject_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_4',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_5',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_6',
        ),
        migrations.AddField(
            model_name='timetable',
            name='FifthPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FifthPeriod', to='timetable.subject', verbose_name='5限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='FirstPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FirstPeriod', to='timetable.subject', verbose_name='1限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='FourthPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='FourthPeriod', to='timetable.subject', verbose_name='4限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='SecondPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SecondPeriod', to='timetable.subject', verbose_name='2限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='SixthPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='SixthPeriod', to='timetable.subject', verbose_name='6限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='ThirdPeriod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='ThirdPeriod', to='timetable.subject', verbose_name='3限'),
            preserve_default=False,
        ),
    ]
